# Generated by Django 3.1.5 on 2021-01-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='news title', max_length=300, verbose_name='TITLE')),
                ('writer', models.CharField(help_text='publisher', max_length=100, verbose_name='WRITER')),
                ('preview', models.TextField(verbose_name='PREVIEW')),
            ],
        ),
    ]
