# Generated by Django 3.1.5 on 2021-01-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210125_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(help_text='news title', max_length=300, unique=True, verbose_name='TITLE'),
        ),
    ]
