# Generated by Django 3.1.5 on 2021-01-27 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210127_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
