# Generated by Django 3.1.5 on 2021-01-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210127_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ('-published_date',), 'verbose_name': 'new', 'verbose_name_plural': 'news'},
        ),
        migrations.AlterField(
            model_name='new',
            name='preview',
            field=models.TextField(verbose_name='PREVIEW'),
        ),
        migrations.AlterModelTable(
            name='new',
            table='news_new',
        ),
    ]
