# Generated by Django 3.1.5 on 2021-01-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210128_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='preview',
            field=models.TextField(unique=True, verbose_name='PREVIEW'),
        ),
    ]
